// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum FeeType {
  low,
  normal,
  priority,
}

enum CurrencyType {
  coin,
  token,
}

class FeeMessage {
  FeeMessage({
    required this.symbol,
    required this.blockchain,
    required this.currencyType,
    required this.receiverAddress,
    required this.sumToSend,
    required this.isTest,
  });

  String symbol;

  String blockchain;

  String currencyType;

  String receiverAddress;

  String sumToSend;

  String isTest;

  Object encode() {
    return <Object?>[
      symbol,
      blockchain,
      currencyType,
      receiverAddress,
      sumToSend,
      isTest,
    ];
  }

  static FeeMessage decode(Object result) {
    result as List<Object?>;
    return FeeMessage(
      symbol: result[0]! as String,
      blockchain: result[1]! as String,
      currencyType: result[2]! as String,
      receiverAddress: result[3]! as String,
      sumToSend: result[4]! as String,
      isTest: result[5]! as String,
    );
  }
}

class SendMessage {
  SendMessage({
    this.symbol,
    required this.blockchainId,
    required this.currencyType,
    required this.walletAddress,
    required this.fee,
    required this.sumToSend,
    required this.receiverAddress,
    this.gasLimit,
    this.gasPrice,
    required this.isTest,
    this.contractAddress,
  });

  String? symbol;

  String blockchainId;

  String currencyType;

  String walletAddress;

  String fee;

  String sumToSend;

  String receiverAddress;

  String? gasLimit;

  String? gasPrice;

  String isTest;

  String? contractAddress;

  Object encode() {
    return <Object?>[
      symbol,
      blockchainId,
      currencyType,
      walletAddress,
      fee,
      sumToSend,
      receiverAddress,
      gasLimit,
      gasPrice,
      isTest,
      contractAddress,
    ];
  }

  static SendMessage decode(Object result) {
    result as List<Object?>;
    return SendMessage(
      symbol: result[0] as String?,
      blockchainId: result[1]! as String,
      currencyType: result[2]! as String,
      walletAddress: result[3]! as String,
      fee: result[4]! as String,
      sumToSend: result[5]! as String,
      receiverAddress: result[6]! as String,
      gasLimit: result[7] as String?,
      gasPrice: result[8] as String?,
      isTest: result[9]! as String,
      contractAddress: result.length > 10 ? result[10] as String? : null,
    );
  }
}

class ValidateAddressMessage {
  ValidateAddressMessage({
    required this.blockchain,
    required this.address,
    required this.isTest,
  });

  String blockchain;

  String address;

  String isTest;

  Object encode() {
    return <Object?>[
      blockchain,
      address,
      isTest,
    ];
  }

  static ValidateAddressMessage decode(Object result) {
    result as List<Object?>;
    return ValidateAddressMessage(
      blockchain: result[0]! as String,
      address: result[1]! as String,
      isTest: result[2]! as String,
    );
  }
}

class FeeResponse {
  FeeResponse({
    required this.type,
    required this.value,
    this.gasLimit,
    this.gasPrice,
  });

  FeeType type;

  String value;

  String? gasLimit;

  String? gasPrice;

  Object encode() {
    return <Object?>[
      type,
      value,
      gasLimit,
      gasPrice,
    ];
  }

  static FeeResponse decode(Object result) {
    result as List<Object?>;
    return FeeResponse(
      type: result[0]! as FeeType,
      value: result[1]! as String,
      gasLimit: result[2] as String?,
      gasPrice: result[3] as String?,
    );
  }
}

class SendTransactionResponse {
  SendTransactionResponse({
    required this.isSuccess,
    this.errorMsg,
  });

  bool isSuccess;

  String? errorMsg;

  Object encode() {
    return <Object?>[
      isSuccess,
      errorMsg,
    ];
  }

  static SendTransactionResponse decode(Object result) {
    result as List<Object?>;
    return SendTransactionResponse(
      isSuccess: result[0]! as bool,
      errorMsg: result[1] as String?,
    );
  }
}

class BlockchainErrorMessage {
  BlockchainErrorMessage({
    required this.code,
    required this.customMessage,
  });

  int code;

  String customMessage;

  Object encode() {
    return <Object?>[
      code,
      customMessage,
    ];
  }

  static BlockchainErrorMessage decode(Object result) {
    result as List<Object?>;
    return BlockchainErrorMessage(
      code: result[0]! as int,
      customMessage: result[1]! as String,
    );
  }
}

class BalanceResponse {
  BalanceResponse({
    required this.data,
    this.errorMessage,
  });

  CurrencyInfoMessage data;

  BlockchainErrorMessage? errorMessage;

  Object encode() {
    return <Object?>[
      data,
      errorMessage,
    ];
  }

  static BalanceResponse decode(Object result) {
    result as List<Object?>;
    return BalanceResponse(
      data: result[0]! as CurrencyInfoMessage,
      errorMessage: result[1] as BlockchainErrorMessage?,
    );
  }
}

class CurrencyInfoMessage {
  CurrencyInfoMessage({
    required this.id,
    required this.icon,
    required this.name,
    required this.networkId,
    this.networkName,
    required this.networkIcon,
    required this.symbol,
    this.contractAddress,
    this.decimalCount,
    this.amount,
    this.address,
    this.publicKey,
    this.chainCode,
    this.isTest,
  });

  String id;

  String icon;

  String name;

  String networkId;

  String? networkName;

  String networkIcon;

  String symbol;

  String? contractAddress;

  int? decimalCount;

  String? amount;

  String? address;

  Uint8List? publicKey;

  Uint8List? chainCode;

  int? isTest;

  Object encode() {
    return <Object?>[
      id,
      icon,
      name,
      networkId,
      networkName,
      networkIcon,
      symbol,
      contractAddress,
      decimalCount,
      amount,
      address,
      publicKey,
      chainCode,
      isTest,
    ];
  }

  static CurrencyInfoMessage decode(Object result) {
    result as List<Object?>;
    return CurrencyInfoMessage(
      id: result[0]! as String,
      icon: result[1]! as String,
      name: result[2]! as String,
      networkId: result[3]! as String,
      networkName: result[4] as String?,
      networkIcon: result[5]! as String,
      symbol: result[6]! as String,
      contractAddress: result[7] as String?,
      decimalCount: result[8] as int?,
      amount: result[9] as String?,
      address: result[10] as String?,
      publicKey: result[11] as Uint8List?,
      chainCode: result[12] as Uint8List?,
      isTest: result[13] as int?,
    );
  }
}

class ExtendedPublicKeyMessage {
  ExtendedPublicKeyMessage({
    required this.blockchain,
    required this.publicKey,
    required this.chainCode,
  });

  String blockchain;

  Uint8List publicKey;

  Uint8List chainCode;

  Object encode() {
    return <Object?>[
      blockchain,
      publicKey,
      chainCode,
    ];
  }

  static ExtendedPublicKeyMessage decode(Object result) {
    result as List<Object?>;
    return ExtendedPublicKeyMessage(
      blockchain: result[0]! as String,
      publicKey: result[1]! as Uint8List,
      chainCode: result[2]! as Uint8List,
    );
  }
}

class CardMessage {
  CardMessage({
    required this.uid,
    required this.isPasswordSet,
    this.publicKey,
    required this.currencyList,
  });

  String uid;

  bool isPasswordSet;

  Uint8List? publicKey;

  List<CurrencyInfoMessage?> currencyList;

  Object encode() {
    return <Object?>[
      uid,
      isPasswordSet,
      publicKey,
      currencyList,
    ];
  }

  static CardMessage decode(Object result) {
    result as List<Object?>;
    return CardMessage(
      uid: result[0]! as String,
      isPasswordSet: result[1]! as bool,
      publicKey: result[2] as Uint8List?,
      currencyList: (result[3] as List<Object?>?)!.cast<CurrencyInfoMessage?>(),
    );
  }
}

class TransactionHistoryRequest {
  TransactionHistoryRequest({
    required this.address,
    this.page,
    required this.type,
    required this.currencyInfo,
  });

  String address;

  String? page;

  int type;

  CurrencyInfoMessage currencyInfo;

  Object encode() {
    return <Object?>[
      address,
      page,
      type,
      currencyInfo,
    ];
  }

  static TransactionHistoryRequest decode(Object result) {
    result as List<Object?>;
    return TransactionHistoryRequest(
      address: result[0]! as String,
      page: result[1] as String?,
      type: result[2]! as int,
      currencyInfo: result[3]! as CurrencyInfoMessage,
    );
  }
}

class TransactionsHistory {
  TransactionsHistory({
    required this.time,
    required this.direction,
    required this.status,
    required this.type,
    required this.value,
    required this.decimals,
    this.txHash,
    this.fromAddress,
    this.toAddress,
  });

  int time;

  int direction;

  int status;

  int type;

  double value;

  int decimals;

  String? txHash;

  String? fromAddress;

  String? toAddress;

  Object encode() {
    return <Object?>[
      time,
      direction,
      status,
      type,
      value,
      decimals,
      txHash,
      fromAddress,
      toAddress,
    ];
  }

  static TransactionsHistory decode(Object result) {
    result as List<Object?>;
    return TransactionsHistory(
      time: result[0]! as int,
      direction: result[1]! as int,
      status: result[2]! as int,
      type: result[3]! as int,
      value: result[4]! as double,
      decimals: result[5]! as int,
      txHash: result.length > 6 ? result[6] as String? : null,
      fromAddress: result.length > 7 ? result[7] as String? : null,
      toAddress: result.length > 8 ? result[8] as String? : null,
    );
  }
}

/// [cardId]卡片ID
/// [data]命令结果
class CommandResponse {
  CommandResponse({
    required this.cardId,
    required this.appletVersionCode,
    required this.appletVersion,
    required this.isActivated,
    required this.resetCount,
    this.data,
  });

  String cardId;

  String appletVersionCode;

  String appletVersion;

  bool isActivated;

  int resetCount;

  Uint8List? data;

  Object encode() {
    return <Object?>[
      cardId,
      appletVersionCode,
      appletVersion,
      isActivated,
      resetCount,
      data,
    ];
  }

  static CommandResponse decode(Object result) {
    result as List<Object?>;
    return CommandResponse(
      cardId: result[0]! as String,
      appletVersionCode: result[1]! as String,
      appletVersion: result[2]! as String,
      isActivated: result[3]! as bool,
      resetCount: result[4]! as int,
      data: result[5] as Uint8List?,
    );
  }
}

/// [command]请求命令数据
/// [checkPwd]是否需要检查密码
/// [checkLock]是否需要检查卡片已锁
/// [ndefLink]是否需要设置ndefLink
/// ///[ndefLink]是否需要设置ndefLink
class SendCommandMessage {
  SendCommandMessage({
    this.appletId,
    this.cardId,
    this.command,
    this.checkLock,
    this.ndefLink,
    this.ndefAar,
    this.cardNo,
    this.checkPwd,
    this.needRun,
    this.needSyscUid,
  });

  Uint8List? appletId;

  String? cardId;

  Uint8List? command;

  bool? checkLock;

  String? ndefLink;
  String? ndefAar;

  String? cardNo;

  bool? checkPwd;

  bool? needRun;

  bool? needSyscUid;

  Object encode() {
    return <Object?>[
      appletId,
      cardId,
      command,
      checkLock,
      ndefLink,
      ndefAar,
      cardNo,
      checkPwd,
      needRun,
      needSyscUid,
    ];
  }

  static SendCommandMessage decode(Object result) {
    result as List<Object?>;
    return SendCommandMessage(
      appletId: result[0] as Uint8List?,
      cardId: result[1] as String?,
      command: result[2] as Uint8List?,
      checkLock: result[3] as bool?,
      ndefLink: result[4] as String?,
      ndefAar: result[5] as String?,
      cardNo: result[6] as String?,
      checkPwd: result[7] as bool?,
      needRun: result[8] as bool?,
      needSyscUid: result[9] as bool?,
    );
  }
}

class ChainKeyMessage {
  ChainKeyMessage({
    required this.blockchainId,
    this.chainId,
    required this.privateKey,
    required this.publicKey,
    required this.address,
  });

  String blockchainId;

  int? chainId;

  String privateKey;

  String publicKey;

  String address;

  Object encode() {
    return <Object?>[
      blockchainId,
      chainId,
      privateKey,
      publicKey,
      address,
    ];
  }

  static ChainKeyMessage decode(Object result) {
    result as List<Object?>;
    return ChainKeyMessage(
      blockchainId: result[0]! as String,
      chainId: result[1] as int?,
      privateKey: result[2]! as String,
      publicKey: result[3]! as String,
      address: result[4]! as String,
    );
  }
}

class ChainKeyInfo {
  ChainKeyInfo({
    required this.cardId,
    required this.chainKeys,
  });

  String cardId;

  List<ChainKeyMessage?> chainKeys;

  Object encode() {
    return <Object?>[
      cardId,
      chainKeys,
    ];
  }

  static ChainKeyInfo decode(Object result) {
    result as List<Object?>;
    return ChainKeyInfo(
      cardId: result[0]! as String,
      chainKeys: (result[1] as List<Object?>?)!.cast<ChainKeyMessage?>(),
    );
  }
}

class SignatureMessage {
  SignatureMessage({
    required this.r,
    required this.s,
    required this.v,
  });

  int r;

  int s;

  int v;

  Object encode() {
    return <Object?>[
      r,
      s,
      v,
    ];
  }

  static SignatureMessage decode(Object result) {
    result as List<Object?>;
    return SignatureMessage(
      r: result[0]! as int,
      s: result[1]! as int,
      v: result[2]! as int,
    );
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is FeeType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CurrencyType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is FeeMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is SendMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is ValidateAddressMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is FeeResponse) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is SendTransactionResponse) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is BlockchainErrorMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is BalanceResponse) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is CurrencyInfoMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is ExtendedPublicKeyMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is CardMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is TransactionHistoryRequest) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is TransactionsHistory) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is CommandResponse) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is SendCommandMessage) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is ChainKeyMessage) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is ChainKeyInfo) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is SignatureMessage) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : FeeType.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CurrencyType.values[value];
      case 131:
        return FeeMessage.decode(readValue(buffer)!);
      case 132:
        return SendMessage.decode(readValue(buffer)!);
      case 133:
        return ValidateAddressMessage.decode(readValue(buffer)!);
      case 134:
        return FeeResponse.decode(readValue(buffer)!);
      case 135:
        return SendTransactionResponse.decode(readValue(buffer)!);
      case 136:
        return BlockchainErrorMessage.decode(readValue(buffer)!);
      case 137:
        return BalanceResponse.decode(readValue(buffer)!);
      case 138:
        return CurrencyInfoMessage.decode(readValue(buffer)!);
      case 139:
        return ExtendedPublicKeyMessage.decode(readValue(buffer)!);
      case 140:
        return CardMessage.decode(readValue(buffer)!);
      case 141:
        return TransactionHistoryRequest.decode(readValue(buffer)!);
      case 142:
        return TransactionsHistory.decode(readValue(buffer)!);
      case 143:
        return CommandResponse.decode(readValue(buffer)!);
      case 144:
        return SendCommandMessage.decode(readValue(buffer)!);
      case 145:
        return ChainKeyMessage.decode(readValue(buffer)!);
      case 146:
        return ChainKeyInfo.decode(readValue(buffer)!);
      case 147:
        return SignatureMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BlockchainApi {
  /// Constructor for [BlockchainApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BlockchainApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 发送拍卡命令
  /// [command]请求命令数据
  /// [checkPwd]是否需要检查密码
  /// [checkLock]是否需要检查卡片已锁
  Future<CommandResponse> scanCardWithCommand(
      SendCommandMessage sendCommandMessage) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.scanCardWithCommand$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[sendCommandMessage]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CommandResponse?)!;
    }
  }

  Future<CardMessage> scanCardAndDerive(List<CurrencyInfoMessage> currencyList,
      String ndefLink, String? cardId, String? cardNo) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.scanCardAndDerive$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
            .send(<Object?>[currencyList, ndefLink, cardId, cardNo])
        as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CardMessage?)!;
    }
  }

  Future<CardMessage> createWalletAndDerive(
      List<CurrencyInfoMessage> currencyList) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.createWalletAndDerive$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[currencyList]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CardMessage?)!;
    }
  }

  Future<void> loadCurrencyInfoList(
      List<CurrencyInfoMessage> currencyList) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.loadCurrencyInfoList$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[currencyList]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  ///初始化钱包
  Future<bool> initScanResponse(String uuid) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.initScanResponse$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[uuid]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  ///添加币种
  Future<bool> addCurrencyList(List<CurrencyInfoMessage> currencyList) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.addCurrencyList$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[currencyList]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  ///获取交易手续费
  Future<List<FeeResponse>> getFee(FeeMessage feeMessage) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.getFee$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[feeMessage]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<FeeResponse>();
    }
  }

  ///发送交易合约
  Future<SendTransactionResponse> sendTransaction(
      SendMessage sendMessage) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.sendTransaction$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[sendMessage]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SendTransactionResponse?)!;
    }
  }

  ///验证钱包地址
  Future<bool> validateAddress(ValidateAddressMessage validateMessage) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.validateAddress$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[validateMessage]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  ///清除原生币种缓存数据
  Future<void> clearLocalCurrency(String cardId, List<String> coinIds) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.clearLocalCurrency$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[cardId, coinIds]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<TransactionsHistory>> loadTransactionHistoryList(
      TransactionHistoryRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.loadTransactionHistoryList$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!
          .cast<TransactionsHistory>();
    }
  }

  ///切换钱包
  Future<bool> changeWallet(
      String cardId, List<CurrencyInfoMessage> currencyList) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.changeWallet$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[cardId, currencyList]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  ///上传奔溃信息
  Future<void> postCatchedException(String error) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.postCatchedException$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[error]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> signLightning(String signText, bool isBtc) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.signLightning$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[signText, isBtc]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<ChainKeyInfo> createChainKeys(List<String> blockchains) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.createChainKeys$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[blockchains]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ChainKeyInfo?)!;
    }
  }

  Future<List<ChainKeyMessage>> getChainKeys(
      String cardId, List<String> blockchains) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.getChainKeys$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[cardId, blockchains]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!
          .cast<ChainKeyMessage>();
    }
  }

  Future<String> signText(
      String blockchainId, String text, int? chainId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.signText$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[blockchainId, text, chainId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> signTransaction(
      String blockchainId, String text, int? chainId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.signTransaction$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[blockchainId, text, chainId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> generateKey() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.generateKey$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> signChallenge(String challenge) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.signChallenge$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[challenge]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> getBitcoinPublicKey() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.getBitcoinPublicKey$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> resetNfcReaderMode() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.resetNfcReaderMode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> getEthPublicKey() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.getEthPublicKey$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> makeAddresses(String networkId, bool isBtc) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.makeAddresses$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[networkId, isBtc]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> bindNetwork() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.bindNetwork$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isVpnActive() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.isVpnActive$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isDualSim() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.chipcore_sdk.BlockchainApi.isDualSim$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

abstract class FlutterClientApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  ///更新数字币余额信息
  bool updateCurrencyInfo(List<BalanceResponse> currencyInfoList);

  static void setUp(
    FlutterClientApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.chipcore_sdk.FlutterClientApi.updateCurrencyInfo$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.chipcore_sdk.FlutterClientApi.updateCurrencyInfo was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<BalanceResponse>? arg_currencyInfoList =
              (args[0] as List<Object?>?)?.cast<BalanceResponse>();
          assert(arg_currencyInfoList != null,
              'Argument for dev.flutter.pigeon.chipcore_sdk.FlutterClientApi.updateCurrencyInfo was null, expected non-null List<BalanceResponse>.');
          try {
            final bool output = api.updateCurrencyInfo(arg_currencyInfoList!);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
