// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum FeeType: Int {
  case low = 0
  case normal = 1
  case priority = 2
}

enum CurrencyType: Int {
  case coin = 0
  case token = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct FeeMessage {
  var symbol: String
  var blockchain: String
  var currencyType: String
  var receiverAddress: String
  var sumToSend: String
  var isTest: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FeeMessage? {
    let symbol = pigeonVar_list[0] as! String
    let blockchain = pigeonVar_list[1] as! String
    let currencyType = pigeonVar_list[2] as! String
    let receiverAddress = pigeonVar_list[3] as! String
    let sumToSend = pigeonVar_list[4] as! String
    let isTest = pigeonVar_list[5] as! String

    return FeeMessage(
      symbol: symbol,
      blockchain: blockchain,
      currencyType: currencyType,
      receiverAddress: receiverAddress,
      sumToSend: sumToSend,
      isTest: isTest
    )
  }
  func toList() -> [Any?] {
    return [
      symbol,
      blockchain,
      currencyType,
      receiverAddress,
      sumToSend,
      isTest,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SendMessage {
  var symbol: String? = nil
  var blockchainId: String
  var currencyType: String
  var walletAddress: String
  var fee: String
  var sumToSend: String
  var receiverAddress: String
  var gasLimit: String? = nil
  var gasPrice: String? = nil
  var isTest: String
  var contractAddress: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendMessage? {
    let symbol: String? = nilOrValue(pigeonVar_list[0])
    let blockchainId = pigeonVar_list[1] as! String
    let currencyType = pigeonVar_list[2] as! String
    let walletAddress = pigeonVar_list[3] as! String
    let fee = pigeonVar_list[4] as! String
    let sumToSend = pigeonVar_list[5] as! String
    let receiverAddress = pigeonVar_list[6] as! String
    let gasLimit: String? = nilOrValue(pigeonVar_list[7])
    let gasPrice: String? = nilOrValue(pigeonVar_list[8])
    let isTest = pigeonVar_list[9] as! String
    let contractAddress: String? = pigeonVar_list.count > 10 ? nilOrValue(pigeonVar_list[10]) : nil

    return SendMessage(
      symbol: symbol,
      blockchainId: blockchainId,
      currencyType: currencyType,
      walletAddress: walletAddress,
      fee: fee,
      sumToSend: sumToSend,
      receiverAddress: receiverAddress,
      gasLimit: gasLimit,
      gasPrice: gasPrice,
      isTest: isTest,
      contractAddress: contractAddress
    )
  }
  func toList() -> [Any?] {
    return [
      symbol,
      blockchainId,
      currencyType,
      walletAddress,
      fee,
      sumToSend,
      receiverAddress,
      gasLimit,
      gasPrice,
      isTest,
      contractAddress,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ValidateAddressMessage {
  var blockchain: String
  var address: String
  var isTest: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ValidateAddressMessage? {
    let blockchain = pigeonVar_list[0] as! String
    let address = pigeonVar_list[1] as! String
    let isTest = pigeonVar_list[2] as! String

    return ValidateAddressMessage(
      blockchain: blockchain,
      address: address,
      isTest: isTest
    )
  }
  func toList() -> [Any?] {
    return [
      blockchain,
      address,
      isTest,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FeeResponse {
  var type: FeeType
  var value: String
  var gasLimit: String? = nil
  var gasPrice: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FeeResponse? {
    let type = pigeonVar_list[0] as! FeeType
    let value = pigeonVar_list[1] as! String
    let gasLimit: String? = nilOrValue(pigeonVar_list[2])
    let gasPrice: String? = nilOrValue(pigeonVar_list[3])

    return FeeResponse(
      type: type,
      value: value,
      gasLimit: gasLimit,
      gasPrice: gasPrice
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      value,
      gasLimit,
      gasPrice,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SendTransactionResponse {
  var isSuccess: Bool
  var errorMsg: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendTransactionResponse? {
    let isSuccess = pigeonVar_list[0] as! Bool
    let errorMsg: String? = nilOrValue(pigeonVar_list[1])

    return SendTransactionResponse(
      isSuccess: isSuccess,
      errorMsg: errorMsg
    )
  }
  func toList() -> [Any?] {
    return [
      isSuccess,
      errorMsg,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BlockchainErrorMessage {
  var code: Int64
  var customMessage: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BlockchainErrorMessage? {
    let code = pigeonVar_list[0] as! Int64
    let customMessage = pigeonVar_list[1] as! String

    return BlockchainErrorMessage(
      code: code,
      customMessage: customMessage
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      customMessage,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BalanceResponse {
  var data: CurrencyInfoMessage
  var errorMessage: BlockchainErrorMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BalanceResponse? {
    let data = pigeonVar_list[0] as! CurrencyInfoMessage
    let errorMessage: BlockchainErrorMessage? = nilOrValue(pigeonVar_list[1])

    return BalanceResponse(
      data: data,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      data,
      errorMessage,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CurrencyInfoMessage {
  var id: String
  var icon: String
  var name: String
  var networkId: String
  var networkName: String? = nil
  var networkIcon: String
  var symbol: String
  var contractAddress: String? = nil
  var decimalCount: Int64? = nil
  var amount: String? = nil
  var address: String? = nil
  var publicKey: FlutterStandardTypedData? = nil
  var chainCode: FlutterStandardTypedData? = nil
  var isTest: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CurrencyInfoMessage? {
    let id = pigeonVar_list[0] as! String
    let icon = pigeonVar_list[1] as! String
    let name = pigeonVar_list[2] as! String
    let networkId = pigeonVar_list[3] as! String
    let networkName: String? = nilOrValue(pigeonVar_list[4])
    let networkIcon = pigeonVar_list[5] as! String
    let symbol = pigeonVar_list[6] as! String
    let contractAddress: String? = nilOrValue(pigeonVar_list[7])
    let decimalCount: Int64? = nilOrValue(pigeonVar_list[8])
    let amount: String? = nilOrValue(pigeonVar_list[9])
    let address: String? = nilOrValue(pigeonVar_list[10])
    let publicKey: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[11])
    let chainCode: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[12])
    let isTest: Int64? = nilOrValue(pigeonVar_list[13])

    return CurrencyInfoMessage(
      id: id,
      icon: icon,
      name: name,
      networkId: networkId,
      networkName: networkName,
      networkIcon: networkIcon,
      symbol: symbol,
      contractAddress: contractAddress,
      decimalCount: decimalCount,
      amount: amount,
      address: address,
      publicKey: publicKey,
      chainCode: chainCode,
      isTest: isTest
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      icon,
      name,
      networkId,
      networkName,
      networkIcon,
      symbol,
      contractAddress,
      decimalCount,
      amount,
      address,
      publicKey,
      chainCode,
      isTest,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ExtendedPublicKeyMessage {
  var blockchain: String
  var publicKey: FlutterStandardTypedData
  var chainCode: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExtendedPublicKeyMessage? {
    let blockchain = pigeonVar_list[0] as! String
    let publicKey = pigeonVar_list[1] as! FlutterStandardTypedData
    let chainCode = pigeonVar_list[2] as! FlutterStandardTypedData

    return ExtendedPublicKeyMessage(
      blockchain: blockchain,
      publicKey: publicKey,
      chainCode: chainCode
    )
  }
  func toList() -> [Any?] {
    return [
      blockchain,
      publicKey,
      chainCode,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CardMessage {
  var uid: String
  var isPasswordSet: Bool
  var publicKey: FlutterStandardTypedData? = nil
  var currencyList: [CurrencyInfoMessage?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CardMessage? {
    let uid = pigeonVar_list[0] as! String
    let isPasswordSet = pigeonVar_list[1] as! Bool
    let publicKey: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])
    let currencyList = pigeonVar_list[3] as! [CurrencyInfoMessage?]

    return CardMessage(
      uid: uid,
      isPasswordSet: isPasswordSet,
      publicKey: publicKey,
      currencyList: currencyList
    )
  }
  func toList() -> [Any?] {
    return [
      uid,
      isPasswordSet,
      publicKey,
      currencyList,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TransactionHistoryRequest {
  var address: String
  var page: String? = nil
  var type: Int64
  var currencyInfo: CurrencyInfoMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TransactionHistoryRequest? {
    let address = pigeonVar_list[0] as! String
    let page: String? = nilOrValue(pigeonVar_list[1])
    let type = pigeonVar_list[2] as! Int64
    let currencyInfo = pigeonVar_list[3] as! CurrencyInfoMessage

    return TransactionHistoryRequest(
      address: address,
      page: page,
      type: type,
      currencyInfo: currencyInfo
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      page,
      type,
      currencyInfo,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TransactionsHistory {
  var time: Int64
  var direction: Int64
  var status: Int64
  var type: Int64
  var value: Double
  var decimals: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TransactionsHistory? {
    let time = pigeonVar_list[0] as! Int64
    let direction = pigeonVar_list[1] as! Int64
    let status = pigeonVar_list[2] as! Int64
    let type = pigeonVar_list[3] as! Int64
    let value = pigeonVar_list[4] as! Double
    let decimals = pigeonVar_list[5] as! Int64

    return TransactionsHistory(
      time: time,
      direction: direction,
      status: status,
      type: type,
      value: value,
      decimals: decimals
    )
  }
  func toList() -> [Any?] {
    return [
      time,
      direction,
      status,
      type,
      value,
      decimals,
    ]
  }
}

/// [cardId]卡片ID
/// [data]命令结果
///
/// Generated class from Pigeon that represents data sent in messages.
struct CommandResponse {
  var cardId: String
  var appletVersionCode: String
  var appletVersion: String
  var isActivated: Bool
  var resetCount: Int64
  var data: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CommandResponse? {
    let cardId = pigeonVar_list[0] as! String
    let appletVersionCode = pigeonVar_list[1] as! String
    let appletVersion = pigeonVar_list[2] as! String
    let isActivated = pigeonVar_list[3] as! Bool
    let resetCount = pigeonVar_list[4] as! Int64
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[5])

    return CommandResponse(
      cardId: cardId,
      appletVersionCode: appletVersionCode,
      appletVersion: appletVersion,
      isActivated: isActivated,
      resetCount: resetCount,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      cardId,
      appletVersionCode,
      appletVersion,
      isActivated,
      resetCount,
      data,
    ]
  }
}

/// [command]请求命令数据
/// [checkPwd]是否需要检查密码
/// [checkLock]是否需要检查卡片已锁
/// [ndefLink]是否需要设置ndefLink
/// ///[ndefLink]是否需要设置ndefLink
///
/// Generated class from Pigeon that represents data sent in messages.
struct SendCommandMessage {
  var appletId: FlutterStandardTypedData? = nil
  var cardId: String? = nil
  var command: FlutterStandardTypedData? = nil
  var checkLock: Bool? = nil
  var ndefLink: String? = nil
  var cardNo: String? = nil
  var checkPwd: Bool? = nil
  var needRun: Bool? = nil
  var needSyscUid: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendCommandMessage? {
    let appletId: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])
    let cardId: String? = nilOrValue(pigeonVar_list[1])
    let command: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])
    let checkLock: Bool? = nilOrValue(pigeonVar_list[3])
    let ndefLink: String? = nilOrValue(pigeonVar_list[4])
    let cardNo: String? = nilOrValue(pigeonVar_list[5])
    let checkPwd: Bool? = nilOrValue(pigeonVar_list[6])
    let needRun: Bool? = nilOrValue(pigeonVar_list[7])
    let needSyscUid: Bool? = nilOrValue(pigeonVar_list[8])

    return SendCommandMessage(
      appletId: appletId,
      cardId: cardId,
      command: command,
      checkLock: checkLock,
      ndefLink: ndefLink,
      cardNo: cardNo,
      checkPwd: checkPwd,
      needRun: needRun,
      needSyscUid: needSyscUid
    )
  }
  func toList() -> [Any?] {
    return [
      appletId,
      cardId,
      command,
      checkLock,
      ndefLink,
      cardNo,
      checkPwd,
      needRun,
      needSyscUid,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChainKeyMessage {
  var blockchainId: String
  var chainId: Int64? = nil
  var privateKey: String
  var publicKey: String
  var address: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChainKeyMessage? {
    let blockchainId = pigeonVar_list[0] as! String
    let chainId: Int64? = nilOrValue(pigeonVar_list[1])
    let privateKey = pigeonVar_list[2] as! String
    let publicKey = pigeonVar_list[3] as! String
    let address = pigeonVar_list[4] as! String

    return ChainKeyMessage(
      blockchainId: blockchainId,
      chainId: chainId,
      privateKey: privateKey,
      publicKey: publicKey,
      address: address
    )
  }
  func toList() -> [Any?] {
    return [
      blockchainId,
      chainId,
      privateKey,
      publicKey,
      address,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChainKeyInfo {
  var cardId: String
  var chainKeys: [ChainKeyMessage?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChainKeyInfo? {
    let cardId = pigeonVar_list[0] as! String
    let chainKeys = pigeonVar_list[1] as! [ChainKeyMessage?]

    return ChainKeyInfo(
      cardId: cardId,
      chainKeys: chainKeys
    )
  }
  func toList() -> [Any?] {
    return [
      cardId,
      chainKeys,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SignatureMessage {
  var r: Int64
  var s: Int64
  var v: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SignatureMessage? {
    let r = pigeonVar_list[0] as! Int64
    let s = pigeonVar_list[1] as! Int64
    let v = pigeonVar_list[2] as! Int64

    return SignatureMessage(
      r: r,
      s: s,
      v: v
    )
  }
  func toList() -> [Any?] {
    return [
      r,
      s,
      v,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FeeType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CurrencyType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return FeeMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return SendMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return ValidateAddressMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return FeeResponse.fromList(self.readValue() as! [Any?])
    case 135:
      return SendTransactionResponse.fromList(self.readValue() as! [Any?])
    case 136:
      return BlockchainErrorMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return BalanceResponse.fromList(self.readValue() as! [Any?])
    case 138:
      return CurrencyInfoMessage.fromList(self.readValue() as! [Any?])
    case 139:
      return ExtendedPublicKeyMessage.fromList(self.readValue() as! [Any?])
    case 140:
      return CardMessage.fromList(self.readValue() as! [Any?])
    case 141:
      return TransactionHistoryRequest.fromList(self.readValue() as! [Any?])
    case 142:
      return TransactionsHistory.fromList(self.readValue() as! [Any?])
    case 143:
      return CommandResponse.fromList(self.readValue() as! [Any?])
    case 144:
      return SendCommandMessage.fromList(self.readValue() as! [Any?])
    case 145:
      return ChainKeyMessage.fromList(self.readValue() as! [Any?])
    case 146:
      return ChainKeyInfo.fromList(self.readValue() as! [Any?])
    case 147:
      return SignatureMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FeeType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CurrencyType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? FeeMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? SendMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ValidateAddressMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? FeeResponse {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? SendTransactionResponse {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? BlockchainErrorMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? BalanceResponse {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? CurrencyInfoMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ExtendedPublicKeyMessage {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? CardMessage {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? TransactionHistoryRequest {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? TransactionsHistory {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? CommandResponse {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? SendCommandMessage {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? ChainKeyMessage {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? ChainKeyInfo {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? SignatureMessage {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BlockchainApi {
  /// 发送拍卡命令
  /// [command]请求命令数据
  /// [checkPwd]是否需要检查密码
  /// [checkLock]是否需要检查卡片已锁
  func scanCardWithCommand(sendCommandMessage: SendCommandMessage, completion: @escaping (Result<CommandResponse, Error>) -> Void)
  func scanCardAndDerive(currencyList: [CurrencyInfoMessage], ndefLink: String, cardId: String?, cardNo: String?, completion: @escaping (Result<CardMessage, Error>) -> Void)
  func createWalletAndDerive(currencyList: [CurrencyInfoMessage], completion: @escaping (Result<CardMessage, Error>) -> Void)
  func loadCurrencyInfoList(currencyList: [CurrencyInfoMessage], completion: @escaping (Result<Void, Error>) -> Void)
  ///初始化钱包
  func initScanResponse(uuid: String) throws -> Bool
  ///添加币种
  func addCurrencyList(currencyList: [CurrencyInfoMessage], completion: @escaping (Result<Bool, Error>) -> Void)
  ///获取交易手续费
  func getFee(feeMessage: FeeMessage, completion: @escaping (Result<[FeeResponse], Error>) -> Void)
  ///发送交易合约
  func sendTransaction(sendMessage: SendMessage, completion: @escaping (Result<SendTransactionResponse, Error>) -> Void)
  ///验证钱包地址
  func validateAddress(validateMessage: ValidateAddressMessage) throws -> Bool
  ///清除原生币种缓存数据
  func clearLocalCurrency(cardId: String, coinIds: [String]) throws
  func loadTransactionHistoryList(request: TransactionHistoryRequest, completion: @escaping (Result<[TransactionsHistory], Error>) -> Void)
  ///切换钱包
  func changeWallet(cardId: String, currencyList: [CurrencyInfoMessage], completion: @escaping (Result<Bool, Error>) -> Void)
  ///上传奔溃信息
  func postCatchedException(error: String, completion: @escaping (Result<Void, Error>) -> Void)
  func signLightning(signText: String, isBtc: Bool, completion: @escaping (Result<String, Error>) -> Void)
  func createChainKeys(blockchains: [String], completion: @escaping (Result<ChainKeyInfo, Error>) -> Void)
  func getChainKeys(cardId: String, blockchains: [String], completion: @escaping (Result<[ChainKeyMessage], Error>) -> Void)
  func signText(blockchainId: String, text: String, chainId: Int64?, completion: @escaping (Result<String, Error>) -> Void)
  func signTransaction(blockchainId: String, text: String, chainId: Int64?, completion: @escaping (Result<String, Error>) -> Void)
  func generateKey(completion: @escaping (Result<String, Error>) -> Void)
  func signChallenge(challenge: String, completion: @escaping (Result<String, Error>) -> Void)
  func getBitcoinPublicKey() throws -> String
  func resetNfcReaderMode() throws
  func getEthPublicKey() throws -> String
  func makeAddresses(networkId: String, isBtc: Bool, completion: @escaping (Result<String, Error>) -> Void)
  func bindNetwork() throws
  func isVpnActive() throws -> Bool
  func isDualSim() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BlockchainApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `BlockchainApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BlockchainApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 发送拍卡命令
    /// [command]请求命令数据
    /// [checkPwd]是否需要检查密码
    /// [checkLock]是否需要检查卡片已锁
    let scanCardWithCommandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.scanCardWithCommand\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanCardWithCommandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sendCommandMessageArg = args[0] as! SendCommandMessage
        api.scanCardWithCommand(sendCommandMessage: sendCommandMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanCardWithCommandChannel.setMessageHandler(nil)
    }
    let scanCardAndDeriveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.scanCardAndDerive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanCardAndDeriveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let currencyListArg = args[0] as! [CurrencyInfoMessage]
        let ndefLinkArg = args[1] as! String
        let cardIdArg: String? = nilOrValue(args[2])
        let cardNoArg: String? = nilOrValue(args[3])
        api.scanCardAndDerive(currencyList: currencyListArg, ndefLink: ndefLinkArg, cardId: cardIdArg, cardNo: cardNoArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanCardAndDeriveChannel.setMessageHandler(nil)
    }
    let createWalletAndDeriveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.createWalletAndDerive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createWalletAndDeriveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let currencyListArg = args[0] as! [CurrencyInfoMessage]
        api.createWalletAndDerive(currencyList: currencyListArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createWalletAndDeriveChannel.setMessageHandler(nil)
    }
    let loadCurrencyInfoListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.loadCurrencyInfoList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadCurrencyInfoListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let currencyListArg = args[0] as! [CurrencyInfoMessage]
        api.loadCurrencyInfoList(currencyList: currencyListArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadCurrencyInfoListChannel.setMessageHandler(nil)
    }
    ///初始化钱包
    let initScanResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.initScanResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initScanResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uuidArg = args[0] as! String
        do {
          let result = try api.initScanResponse(uuid: uuidArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initScanResponseChannel.setMessageHandler(nil)
    }
    ///添加币种
    let addCurrencyListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.addCurrencyList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addCurrencyListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let currencyListArg = args[0] as! [CurrencyInfoMessage]
        api.addCurrencyList(currencyList: currencyListArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addCurrencyListChannel.setMessageHandler(nil)
    }
    ///获取交易手续费
    let getFeeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.getFee\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFeeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let feeMessageArg = args[0] as! FeeMessage
        api.getFee(feeMessage: feeMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getFeeChannel.setMessageHandler(nil)
    }
    ///发送交易合约
    let sendTransactionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.sendTransaction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTransactionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sendMessageArg = args[0] as! SendMessage
        api.sendTransaction(sendMessage: sendMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendTransactionChannel.setMessageHandler(nil)
    }
    ///验证钱包地址
    let validateAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.validateAddress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      validateAddressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let validateMessageArg = args[0] as! ValidateAddressMessage
        do {
          let result = try api.validateAddress(validateMessage: validateMessageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      validateAddressChannel.setMessageHandler(nil)
    }
    ///清除原生币种缓存数据
    let clearLocalCurrencyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.clearLocalCurrency\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearLocalCurrencyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cardIdArg = args[0] as! String
        let coinIdsArg = args[1] as! [String]
        do {
          try api.clearLocalCurrency(cardId: cardIdArg, coinIds: coinIdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearLocalCurrencyChannel.setMessageHandler(nil)
    }
    let loadTransactionHistoryListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.loadTransactionHistoryList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadTransactionHistoryListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! TransactionHistoryRequest
        api.loadTransactionHistoryList(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadTransactionHistoryListChannel.setMessageHandler(nil)
    }
    ///切换钱包
    let changeWalletChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.changeWallet\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      changeWalletChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cardIdArg = args[0] as! String
        let currencyListArg = args[1] as! [CurrencyInfoMessage]
        api.changeWallet(cardId: cardIdArg, currencyList: currencyListArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      changeWalletChannel.setMessageHandler(nil)
    }
    ///上传奔溃信息
    let postCatchedExceptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.postCatchedException\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      postCatchedExceptionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let errorArg = args[0] as! String
        api.postCatchedException(error: errorArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      postCatchedExceptionChannel.setMessageHandler(nil)
    }
    let signLightningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.signLightning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signLightningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let signTextArg = args[0] as! String
        let isBtcArg = args[1] as! Bool
        api.signLightning(signText: signTextArg, isBtc: isBtcArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signLightningChannel.setMessageHandler(nil)
    }
    let createChainKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.createChainKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChainKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let blockchainsArg = args[0] as! [String]
        api.createChainKeys(blockchains: blockchainsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createChainKeysChannel.setMessageHandler(nil)
    }
    let getChainKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.getChainKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getChainKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cardIdArg = args[0] as! String
        let blockchainsArg = args[1] as! [String]
        api.getChainKeys(cardId: cardIdArg, blockchains: blockchainsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getChainKeysChannel.setMessageHandler(nil)
    }
    let signTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.signText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let blockchainIdArg = args[0] as! String
        let textArg = args[1] as! String
        let chainIdArg: Int64? = nilOrValue(args[2])
        api.signText(blockchainId: blockchainIdArg, text: textArg, chainId: chainIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signTextChannel.setMessageHandler(nil)
    }
    let signTransactionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.signTransaction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signTransactionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let blockchainIdArg = args[0] as! String
        let textArg = args[1] as! String
        let chainIdArg: Int64? = nilOrValue(args[2])
        api.signTransaction(blockchainId: blockchainIdArg, text: textArg, chainId: chainIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signTransactionChannel.setMessageHandler(nil)
    }
    let generateKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.generateKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateKeyChannel.setMessageHandler { _, reply in
        api.generateKey { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateKeyChannel.setMessageHandler(nil)
    }
    let signChallengeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.signChallenge\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signChallengeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let challengeArg = args[0] as! String
        api.signChallenge(challenge: challengeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signChallengeChannel.setMessageHandler(nil)
    }
    let getBitcoinPublicKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.getBitcoinPublicKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBitcoinPublicKeyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBitcoinPublicKey()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBitcoinPublicKeyChannel.setMessageHandler(nil)
    }
    let resetNfcReaderModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.resetNfcReaderMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetNfcReaderModeChannel.setMessageHandler { _, reply in
        do {
          try api.resetNfcReaderMode()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetNfcReaderModeChannel.setMessageHandler(nil)
    }
    let getEthPublicKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.getEthPublicKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getEthPublicKeyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getEthPublicKey()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getEthPublicKeyChannel.setMessageHandler(nil)
    }
    let makeAddressesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.makeAddresses\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      makeAddressesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let networkIdArg = args[0] as! String
        let isBtcArg = args[1] as! Bool
        api.makeAddresses(networkId: networkIdArg, isBtc: isBtcArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      makeAddressesChannel.setMessageHandler(nil)
    }
    let bindNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.bindNetwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      bindNetworkChannel.setMessageHandler { _, reply in
        do {
          try api.bindNetwork()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      bindNetworkChannel.setMessageHandler(nil)
    }
    let isVpnActiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.isVpnActive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isVpnActiveChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isVpnActive()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isVpnActiveChannel.setMessageHandler(nil)
    }
    let isDualSimChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chipcore_sdk.BlockchainApi.isDualSim\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isDualSimChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isDualSim()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isDualSimChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FlutterClientApiProtocol {
  ///更新数字币余额信息
  func updateCurrencyInfo(currencyInfoList currencyInfoListArg: [BalanceResponse], completion: @escaping (Result<Bool, PigeonError>) -> Void)
}
class FlutterClientApi: FlutterClientApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  ///更新数字币余额信息
  func updateCurrencyInfo(currencyInfoList currencyInfoListArg: [BalanceResponse], completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.chipcore_sdk.FlutterClientApi.updateCurrencyInfo\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([currencyInfoListArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
}
